# Run tests
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9"]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Graphviz
        run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y graphviz
         elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "Graphviz tests will now run on Windows"
         fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m pip install poetry
          poetry install
      - name: Run MyPy Checks
        run: poetry run mypy src
      - name: Run Nose Tests
        run: poetry run nosetests -v ./


