# Run tests
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9"]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Graphviz
        run: |
         echo $RUNNER_OS
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y graphviz
         else
             echo "Graphviz tests will only run for ubuntu-latest"
         fi
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m pip install poetry
          poetry install
      - name: Run MyPy Checks
        run: poetry run mypy src
      - name: Run Tests
        run: |
          echo $RUNNER_OS
          if [ "$RUNNER_OS" == "Linux" ]; then
               poetry run python -m nose -v -w ./tests
          else
              poetry run python -m unittest -v
          fi
        shell: bash


